apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: queue-service
          image: "pastelpunkregistry.azurecr.io/queue-service:latest"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 8080
              name: queue-service
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
spec:
  ports:
    - port: 8080
  selector:
    app: queue-service
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service-load-balancer
spec:
  loadBalancerIP: 52.188.34.79
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: queue-service
